### ISSUE TITLE
Lack support for "NULL" keyword and file I/O

### ISSUE THREAD

**Issue by D15190304050** [ShivamSarodia/ShivyC#107]
![not support for file io](https://user-images.githubusercontent.com/15382702/49790885-3ad1f880-fd6a-11e8-8cf6-951da78cfe85.png)
![not support for null](https://user-images.githubusercontent.com/15382702/49790886-3b6a8f00-fd6a-11e8-8142-42944d1b1a91.png)

Fig.2 shows that your compiler cannot identify the "NULL" keyword, which is a quite important keyword in C. Then I modified my code, which makes error in Fig.1. Your compiler doesn't support file I/O. Can you fix this?

**Comment by D15190304050** [comment]
It shows that your compiler cannot identify the "NULL" keyword, which is a quite important keyword in C. Then I modified my code, which makes error again. Your compiler doesn't support file I/O. Can you fix this?
![bug](https://user-images.githubusercontent.com/15382702/49791158-cf3c5b00-fd6a-11e8-8ccd-8df812fd243e.png)

**Comment by ShivamSarodia** [comment]
Hi @D15190304050, thanks for your message!

- The NULL keyword is defined as a macro in stddef.h in a standard implementations. Since ShivyC does not support macros yet, NULL does not work. As a workaround in the meantime, you can create a variable named NULL and set it equal to 0.
- File I/O should be supported in general -- see [this test](https://github.com/ShivamSarodia/ShivyC/blob/master/tests/general_tests/trie/trie.c) for an example that uses `fopen` for file reading. Perhaps you're encountering a bug in ShivyC? If you could you send over `WordCount.c`, I can take a look.

Super exciting to see you using ShivyC. If I may ask, what's your use case for ShivyC?

**Comment by D15190304050** [comment]
> Hi @D15190304050, thanks for your message!
> 
> * The NULL keyword is defined as a macro in stddef.h in a standard implementations. Since ShivyC does not support macros yet, NULL does not work. As a workaround in the meantime, you can create a variable named NULL and set it equal to 0.
> * File I/O is a supported feature in general -- see [this test](https://github.com/ShivamSarodia/ShivyC/blob/master/tests/general_tests/trie/trie.c) for an example that uses `fopen` for file reading. Perhaps you're encountering a bug in ShivyC? If you could you send over `WordCount.c`, I can take a look.
> 
> Super exciting to see you using ShivyC. If I may ask, what's your use case for ShivyC?

Thank you for your reply. File I/O has no problem, I found a bug in my program.

Sorry for reply you so late.
